# Dev environment overrides
namespace: doctalk

api:
  image:
    tag: latest
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

web:
  image:
    tag: latest
  replicaCount: 2

postgres:
  enabled: true
  storage: 10Gi

ingress:
  hosts:
    api: api.doctalk.ng
    web: doctalk.ng

config:
  nodeEnv: production
  logLevel: debug
  corsOrigins: "https://doctalk.ng"
  nextPublicApiUrl: "https://api.doctalk.ng"
