apiVersion: v1
kind: ConfigMap
metadata:
  name: doctalk-config
  namespace: doctalk
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://doctalk.ng,https://api.doctalk.ng"
  NEXT_PUBLIC_API_URL: "https://api.doctalk.ng"
  PORT: "4000"
