apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: doctalk
  labels:
    app: postgres
    component: database
    app.kubernetes.io/part-of: doctalk
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
