apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: doctalk
  labels:
    app: web
    component: frontend
    app.kubernetes.io/part-of: doctalk
spec:
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
      name: http
